### ISSUE TITLE
Polish the Reminders

### ISSUE THREAD

**Issue by ShawnClake** [ShawnClake/Naps#4]
Since most of this assignment has to do with reminders, make sure the reminder stuff is working properly.  I can't remember exactly how you were adding reminders, but for this stage they cannot be added globally. In other words, each user must have their own set of reminders. Depending on time it would be best if these could be saved to a file.

For example, in a file where each row represents a user, you could store the user ID and a list of their reminders. You would just need a way to import/export to that file.

If there isn't enough time to do this, then just ensure each user has their own set of Reminders as indicated by the 'reminders' class property on the User model.

**Comment by SamPhil** [comment]
Ok now my section makes sense. Once this is finalized I`ll know how to move forward. Uysie where are you on this?
