### ISSUE TITLE
Implement the Reminder Manager

### ISSUE THREAD

**Issue by ShawnClake** [ShawnClake/Naps#5]
Since there isn't any fit-bit stuff on this assignment, do the Reminder Manager class.

* getUsersReminders just returns the reminders attached to the User model passed to the method. Check with Uys as he is working on refactoring the reminders a little bit to allow separate lists of reminders for each user.

* addReminderToUser just adds an additional reminder to the user model passed to the method.

* addReminderAll adds an additional reminder to all of the users.

* isAuthorized is a private method used to see if a user is in the same user group as another user in order to add a reminder to them. For example, if User A wants to add a reminder to User B, then User A and B must be in the same user group.

**Comment by SamPhil** [comment]
Thoughts on this;
-I think addReminderAll should take the (User, UserGroup, Reminder) that way the reminder is added to all users within the UserGroup without having to have a isAuthorized method at al

**Comment by ShawnClake** [comment]
Reid stated that adding reminders to all users would not matter upon their user group. In other words, every single signed up user should receive the reminder when set via addReminderAll

isAuthorized is more meant for addReminderToUser. In this case, you are adding a single reminder to a single user.

**Comment by SamPhil** [comment]
Did Reid actually say that? I think that's terrible design. I would hate that feature.

**Comment by ShawnClake** [comment]
In his assignment 3 feedback he didn't say anything about user groups in the first place. In my UML diagram, I added them because it didn't make sense for any user to add a reminder to any other user.

However, in that same feedback section he indicated a reminder should be able to be added to all users at once.
